In [1]:
%config Completer.use_jedi = False
%config IPCompleter.greedy=True

import pandas as pd
import numpy as np

In [2]:
raw = pd.read_excel('BBDD_CARDERNETAS_CORREGIDO.xlsx', sheet_name="sin duplicados", dtype=str)
print(raw.columns)
print(raw.info())

Index(['ID', 'AM', 'A', 'TIPO', 'CALLE', 'Nº', 'BARRIO', 'CIUDAD', 'M2', 'USO',
       ...
       'Unnamed: 143', 'Unnamed: 144', 'Unnamed: 145', 'Unnamed: 146',
       'Unnamed: 147', 'Unnamed: 148', 'Unnamed: 149', 'Unnamed: 150',
       'Unnamed: 151', 'Unnamed: 152'],
      dtype='object', length=153)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37115 entries, 0 to 37114
Columns: 153 entries, ID to Unnamed: 152
dtypes: object(153)
memory usage: 43.3+ MB
None

In [3]:
arr = raw['CALLE'].str.strip().str.split(' ').str[0].sort_values().unique()
df = pd.DataFrame(data=arr, index=None, columns=['Prefijo'])
df.to_excel('prefijo_calles.xlsx', index=None)

In [4]:
raw['CALLE'].str.strip(" -.\n").str.split(' ').str[0].value_counts().sort_index().to_excel('prefijo_calles.xlsx', index_label=["Calle"])

In [5]:
raw['STREET_PREFIX'] = raw['CALLE'].str.strip(" -.\n").str.split(' ').str[0]

In [6]:
raw['TIPO_CLEAN'] = raw['TIPO'].str.strip(' .').str.upper()
raw['TIPO_CLEAN']

0        ESTRADA
1           BECO
2        ESTRADA
3            RUA
4            RUA
          ...
37110        RUA
37111        RUA
37112        RUA
37113        RUA
37114        RUA
Name: TIPO_CLEAN, Length: 37115, dtype: object

In [7]:
# raw['TIPO_CLEAN'].sort_index().value_counts().to_excel('tipos_via.xlsx')
raw['TIPO_CLEAN'].value_counts(sort=False).sort_index().to_excel('tipos_via.xlsx')

In [8]:
raw['SLUG'] = raw['AM'].map(str) + '-' + raw['A'].map(str) + '-' + raw['TIPO_CLEAN'].map(str) + '-' + raw['CALLE'].map(str).str.strip() + '-' + raw['Nº'].map(str) + '-' + raw['BARRIO'].map(str)+ '-' + raw['CIUDAD'].map(str)
# raw['SLUG'] = raw['SLUG'].replace(to_replace=r'[\s\.,ºª]', value='', regex=True)
raw['SLUG'] = raw['SLUG'].replace(regex={r'[\.,ºª]': '', r'\s': '_'})
print(raw['SLUG'].size)
print(raw['SLUG'].unique().size)

37115
35376

In [9]:
# raw.iloc[:, 12:15] // first owner
# raw.iloc[:, 150:153] // last owner

In [20]:
import uuid
import random

def random_uuid():
    return uuid.UUID(bytes=bytes(random.getrandbits(8) for _ in range(16)), version=4)

random.seed('portugal-data')
raw['BUILDING_ID'] = [random_uuid() for _ in range(len(raw.index))]
raw['BUILDING_ID']

0        4de1844d-9dc9-48cf-aede-ca17bfcf6828
1        eaf87a06-6745-40c4-8550-a35e0728ea65
2        504da315-3599-44d3-89f6-2c825de70e1b
3        39317045-179a-420c-937a-35702874e6a0
4        ce1791ca-b45b-416f-bcb1-a8e8890267e9
                         ...
37110    fcb68077-0be7-4ff0-8a81-e7e21193503c
37111    749b6ec5-9dd7-4d3a-8928-c61b8b42b805
37112    2211a5ba-fc30-4550-8707-830862e4f638
37113    e7a61275-5bb1-4065-a10f-8e657d41894b
37114    da1518ed-1921-4b1e-a6b5-dae41dc6ddbf
Name: BUILDING_ID, Length: 37115, dtype: object

In [11]:
raw.to_csv('portugal_ready.csv', sep=";")

In [12]:
phones = pd.read_excel('TELEFONOS.xlsx', sheet_name='sin duplicados')
phones

,Nº C,1,2,3,4,5,6,7,8,9,...,19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,100320708,914642802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100401481,226187147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,101040423,962995764,963059150,936423287,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,101903014,964248575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,102297711,914937073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19274,284253235,219619660,968624867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19275,284706671,934772869,213901686,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19276,290142601,920247290,219240645,219240878,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19277,290436079,912601262,213950436,213870214,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19278,296824275,965701536,218873211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# phones[phones['Nº C'].duplicated()]
# phones[phones['Nº C'].map(str) == '273150758']
uniques_phones = phones.drop(7506)
uniques_phones = uniques_phones.drop(7485)
uniques_phones = uniques_phones.drop(7632)
uniques_phones[uniques_phones['Nº C'].duplicated()]
uniques_phones.to_csv('phones.csv', sep=';', header=None, index=None)
# 121992403
# 143989235
# 273150758

In [36]:
# raw[raw['SLUG'].duplicated()]['SLUG']
# print(raw.columns.to_list())
raw[raw['SLUG'] == '1398-544-ESTRADA-DO_LOUREIRO-28-ESTRELA-LISBOA'].iloc[:, 12+3*7:]

,NOMBRE.7,ID FISCAL.7,MORADA.7,NOMBRE.8,ID FISCAL.8,MORADA.8,NOMBRE.9,ID FISCAL.9,MORADA.9,NOMBRE.10,...,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,STREET_PREFIX,TIPO_CLEAN,SLUG,BUILDING_ID
13422,ANA PAULA CORDEIRO GONÇALVES PEREIRA,NaN,185151779,"ALTO DO CARVALHÃO, N.o 18, 2o - ESQ., LISBOA,...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,DO,ESTRADA,1398-544-ESTRADA-DO_LOUREIRO-28-ESTRELA-LISBOA,503c7ba6-af55-4030-acb8-a951b09f703b